---
title: "**About**"
output: 
  html_document:
      toc: true
      toc_float: true
---

## Overview


<iframe width="560" height="315" src="https://www.youtube.com/embed/DqD5n2aiMk8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Project Inspiration and Goals
Electronic cigarette (e-cigarette) use has become a growing public health concern. As of October 29, 2019, there have been 1,888 cases of lung injury due to e-cigarette use, or vaping, reported to the CDC from 49 states [(1)](https://www.cdc.gov/tobacco/basic_information/e-cigarettes/severe-lung-disease.html). Medical officials have become increasingly interested in the development of lung disease among users; however, there is still little known about the deleterious effects of e-cigarette use. While e-cigarettes and vapes were initially intended for current smokers to reduce tobacco dependency, these products have been massively marketed to teenagers with no smoking history. The goal of this project is to elucidate trends in e-cigarette use among youth in order to inform the development and implementation of preventive and therapeutic interventions. To do so, we aim to answer three questions. 

1. How has e-cigarette use among youth changed from 2011-2018?  
We wish to visualize patterns in e-cigarette use over time. While we know from outside sources that e-cigarettes have become very popular over the past few years, we hope to demonstrate this trend through visualizations to gain insights into when and to what degree e-cigarette use has changed from 2011-2018.

2. What factors put an individual at greatest risk of e-cigarette use?  
We will consider several demographics such as age, sex and race, as well as cigarette consumption, perception towards the harm of e-cigarettes, and the frequency of e-cigarette ads viewed.

3. How has legislation changed over time to address the growing rate of e-cigarette use throughout the United States?  
To build on previous studies, we want to consider the geographic component of e-cigarette use and attempts to reduce youth access to e-cigarettes.


## About Us

This project was completed by Rebecca Silva, Madison Stoms, Robert Tumasian, and Charlotte Fowler. We are four PhD students studying biostatistics at Columbia Univeristy's Mailman School of Public Health. The project was completed as part of our Data Science I course taken Fall 2019. 