---
title: "Exploration Across States: Prevalence and Legislatation"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(maps)
library(plotly)
library(gganimate)
library(rvest)
library(srvyr)
library(httr)
```


```{r, include= FALSE}
url = "https://www.cdc.gov/pcd/issues/2019/18_0362.htm"

state_prev_xml = read_html(url)

state_prev = 
  (state_prev_xml %>% html_nodes(css = "table")) %>% 
  .[[1]] %>%
  html_table(fill = TRUE) 

names(state_prev)[1] = "state"
names(state_prev)[2] = "ex1"
names(state_prev)[3] = "ex2"
names(state_prev)[4] = "ex3"
names(state_prev)[5] = "ex4"
names(state_prev)[6] = "ex5"
names(state_prev)[8] = "total_prev"
names(state_prev)[9] = "male_prev"
names(state_prev)[10] = "female_prev"

state_prev = state_prev %>% 
  select(state, total_prev, male_prev, female_prev) %>% 
  slice(3:n())  %>% 
  separate(state, into = c("state", "n"), "\\(") %>% 
  separate(total_prev, into = c("total_prev", "total_CI"), "\\(" ) %>% 
  separate(male_prev, into = c("male_prev", "male_CI"), "\\(" ) %>% 
  separate(female_prev, into = c("female_prev", "female_CI"), "\\(" ) %>% 
  select(state, total_prev, male_prev, female_prev)

state_prev = 
  state_prev %>% 
  mutate(state = str_to_lower(state), 
         state = trimws(state), 
         total_prev = as.numeric(total_prev), 
         male_prev = as.numeric(male_prev), 
         female_prev = as.numeric(female_prev))

# state data
states = map_data("state") %>% 
  rename(state = region) %>% 
  select(state, everything(), -subregion)


# joining datasets 
map_state_prev = left_join(states, state_prev, by = "state")
```

```{r, include=FALSE}
## prevalence map data
prev_plot = map_state_prev  %>% 
  rename(prevalence = "total_prev") %>% 
  ggplot() +
  geom_polygon(aes( x = long, y = lat, group = group, fill = prevalence, subgroup = state), color = "white") +
  scale_fill_continuous(low = "white", high = "red", na.value = "black") +
  labs(
    title = "Prevalence of E-cigarette use by state",
    fill = "Prevalence", 
    x = "", 
    y = "")
```


```{r}
# legislation data
#legislation_data = 
 # read_csv("./Data/legislation_data.csv")

# legislation data
legislation_data = read_csv("CDC_State_ECigarette_Legislation_Youth_Access.csv") %>%
  janitor::clean_names() %>% 
  select(-c(data_source, comments, display_order:provision_id))
```



```{r, include= FALSE}
# legislation map data
legislation_n = legislation_data %>% 
  group_by(year, state, effective_date) %>% 
  summarise(n_legislation = n()) %>% 
  filter(!is.na(effective_date)) %>% 
  select(-effective_date)

map_data_leg = left_join(states, legislation_n, by = "state")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r,echo=FALSE}
ggplotly(prev_plot, tooltip = c("state", "prevalence")) 
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
years = unique(legislation_n %>% pull(year))

# selectInput widget
selectInput(
  "year_choice", 
  label = h3("Select year"),
  choices = years, selected = 2018)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo = FALSE}

renderPlot({ 
  map_data_leg %>% 
  filter(year == input$year_choice) %>% 
  ggplot() +
  geom_polygon(aes( x = long, y = lat, group = group, fill = n_legislation), color = "white") +
  scale_fill_continuous(low = "white", high = "red", na.value = "black")
})

```

### Chart C


```{r}
#ecig data (read_cvs assumes some cols as all NA )
ecig_data = read.csv("./Data/ecig_data.csv")

#creating survey object 
srv_ecig = ecig_data %>% 
  mutate(id = row_number()) %>% 
   as_survey_design(id = id, wt = as.numeric(weight))
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
year = c("2015", "2016", "2017" , "2018")

# selectInput widget
selectInput(
  "year_choice", 
  label = h3("Select year"),
  choices = year, selected = 2018)

```




Column {.sidebar}
-----------------------------------------------------------------------

```{r}
year = c("2015", "2016", "2017" , "2018")

# selectInput widget
selectInput(
  "year_choice", 
  label = h3("Select year"),
  choices = year, selected = 2018)

```


```{r}
row = nrow(ecig_data)
renderPlot({
  srv_ecig %>% 
    mutate(one = rep(1, row),
          quit_cig = fct_relevel(quit_cig, c("not a smoker", "next 30 days", "next 6 months", "within 1 year", "over 1 year", "no"))) %>% 
    filter(quit_cig != "not a smoker") %>% 
    filter(!is.na(quit_cig), !is.na(ecigs_past_month)) %>% 
    filter(year == input$year_choice) %>% 
    group_by(quit_cig, ecigs_past_month) %>% 
    summarise(n = survey_total(one)) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes( x = quit_cig, 
              y = prop, 
              fill = ecigs_past_month)) + 
    geom_bar(position ="dodge", 
           stat ="identity") +
    theme(legend.position = "bottom", 
        axis.text.x = element_text(angle = 90), 
        plot.title = element_text(hjust = .5)) +
    scale_fill_viridis(discrete = T) +
    labs(
      title = "E-Cig Use with proportion eagerness \n to quit smoking cigarettes",
      x = "When are you trying to quit?",
      y = "Proportion", 
      fill = "Ecig frequency/month")
})
```

