---
title: "E-Cigarettes"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(maps)
library(plotly)
library(rvest)
library(srvyr)
library(httr)
```

```{r}
#library(rsconnect)
# rsconnect::deployApp("./shiny_legislation_final.Rmd")
# rmarkdown::render("shiny_legislation_final.Rmd", output_format = "flexdashboard::flex_dashboard") # to get html 
```


```{r data, include = FALSE}
# legislation data
legislation_data = read_csv("CDC_State_ECigarette_Legislation_Youth_Access.csv") %>%
  janitor::clean_names() %>% 
  filter(year %in% c(2011:2018),
         !location_desc %in% c('American Samoa', 'Guam', 'Marshall Islands',
                               'Northern Mariana Islands', 'Palau', 'Puerto Rico',
                               'U.S. Virgin Islands', 'District of Columbia'), 
         !is.na(effective_date)) %>% 
  rename(state = location_desc) %>% 
  select(-c(data_source, comments, display_order:provision_id))

# legislation map data
legislation_n = legislation_data %>% 
  group_by(year, state) %>% 
  summarise(n_legislations = n()) 


state_abb = state.name
names(state_abb) = state.abb

# for each year need all states, just NAs if not there
# first find states missing in each year 
all_states = unname(state_abb)
index = 0
list = vector(mode = "list", 
              length = n_distinct(legislation_n %>% pull(year)))
for (yr in c(2011:2018)){
  index = index + 1
  states_not_na = legislation_n %>% 
    filter(year == yr) %>% 
    pull(state)
  missing_states = all_states[!all_states %in% states_not_na]
  list[[index]] = tibble(
    state = missing_states, 
    year = c(rep(yr, length(missing_states))),  
    n_legislations = 0
  )
}
add_df = bind_rows(list)
legislation_full = bind_rows(legislation_n, add_df)

```

Legislation Map
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
years = unique(legislation_full %>% pull(year))

# selectInput widget
selectInput(
  "year_choice", 
  label = h3("Select year"),
  choices = years, selected = 2018)
```

It is evident that the number of legislations have increased amoung all states from 2011 to 2018. Refer to the "Explore" page to look at the specific legislations that became effective each year. 


Column {.tabset .tabset-fade}
-------------------------------------

### Legislation By Year

```{r}
# plot map
renderPlotly({
  legislation_year = legislation_full %>% 
    filter(year ==input[["year_choice"]])

  legislations =  setNames(legislation_year$n_legislations,
                     legislation_year$state)
  g = list(
    scope = 'usa',
    projection = list(type = "state"),
    showlakes = TRUE,
    lakecolor = toRGB('white')
  )

  plot_geo() %>%
    add_trace(
      z = ~legislations, 
      text = state.name, 
      colors = "Blues", 
      span = I(0),
      locations = state.abb, 
      locationmode = 'USA-states',
      showlegend = FALSE
    ) %>%
    layout(geo = g, 
           title = "Number of Legislations in the US")

})
```


### Description

Explore
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}

#years = unique(legislation_full %>% pull(year))

# selectInput widget
selectInput(
  "year_table_choice", 
  label = h3("Select year"),
  choices = years, selected = 2011)

provision_choice = legislation_data %>% distinct(measure_desc) %>% pull()

# radioButtons widget
radioButtons(
  "provision_choice", 
  label = h3("Choose provision"),
  choices = provision_choice, selected = "E-Cigarette Sales")

provision_grp_choice = legislation_data %>% distinct(provision_group_desc) %>% pull()

# radioButtons widget
radioButtons(
  "provision_grp_choice", 
  label = h3("Choose provision type"),
  choices = provision_grp_choice, selected = "Restrictions")

```
    
    
Column {.tabset}
-----------------------------------------------------------------------

```{r}
data = legislation_data %>% 
  filter(provision_value != "No Provision") %>% 
  group_by(year, state, measure_desc, provision_group_desc, provision_desc, provision_value) %>% 
  summarize(n = n()) %>% ungroup()


renderTable({
data %>%  
  filter(year == input[["year_table_choice"]], 
         measure_desc == input[["provision_choice"]],
         provision_group_desc == input[["provision_grp_choice"]]) %>% 
  ungroup() %>% 
  filter(provision_desc != "Minimum Age")  %>% 
  distinct(state, provision_desc, provision_value) 
})
```


Prevalence 
===================================== 


```{r, include= FALSE}
url = "https://www.cdc.gov/pcd/issues/2019/18_0362.htm"

state_prev_xml = read_html(url)

state_prev = 
  (state_prev_xml %>% html_nodes(css = "table")) %>% 
  .[[1]] %>%
  html_table(fill = TRUE) 

names(state_prev)[1] = "state"
names(state_prev)[2] = "ex1"
names(state_prev)[3] = "ex2"
names(state_prev)[4] = "ex3"
names(state_prev)[5] = "ex4"
names(state_prev)[6] = "ex5"
names(state_prev)[8] = "total_prev"
names(state_prev)[9] = "male_prev"
names(state_prev)[10] = "female_prev"

state_prev = state_prev %>% 
  select(state, total_prev, male_prev, female_prev) %>% 
  slice(3:n())  %>% 
  separate(state, into = c("state", "n"), "\\(") %>% 
  separate(total_prev, into = c("total_prev", "total_CI"), "\\(" ) %>% 
  separate(male_prev, into = c("male_prev", "male_CI"), "\\(" ) %>% 
  separate(female_prev, into = c("female_prev", "female_CI"), "\\(" ) %>%
  select(state, total_prev, male_prev, female_prev)

state_prev = 
  state_prev %>% 
  mutate(state = trimws(state), 
         total_prev = as.numeric(total_prev), 
         male_prev = as.numeric(male_prev), 
         female_prev = as.numeric(female_prev)) %>% 
  filter(state != "District of Columbia")


# state data
#states = map_data("state") %>% 
 # rename(state = region) %>% 
 # select(state, everything(), -subregion)


# joining datasets 
#map_state_prev = left_join(states, state_prev, by = "state")
```


Row {.tabset}
-----------------------------------------------------------------------

### E-Cigarette Prevalence in Adults 

```{r }

#renderPlotly({
  Prevalence =  setNames(state_prev$total_prev,
                     state_prev$state)
  p = list(
    scope = 'usa',
    projection = list(type = "state"),
    showlakes = TRUE,
    lakecolor = toRGB('white')
  )

  plot_geo() %>%
    add_trace(
      z = ~Prevalence, 
      text = state.name, 
      colors = "Reds", 
      span = I(0),
      locations = state.abb, 
      locationmode = 'USA-states',
      showlegend = FALSE
    ) %>%
    layout(geo = p, 
           title = "Prevalence of E-Cigs in Adults")

#})
  
```

### Legislations and Prevalence 

```{r}
new  = legislation_full %>% 
    group_by(state) %>% 
    summarise(total_legislations = sum(n_legislations))

test = merge(new, state_prev, by = "state")

test %>% 
    mutate(text_label = str_c(state, ": ", total_legislations, " total legislations")) %>% 
    plot_ly(
        x = ~total_prev, 
        y = ~total_legislations, 
        type = "scatter", 
        mode = "markers", 
        color = ~state, 
        text = ~text_label, alpha = 0.5
    ) %>% 
    layout(title = "Total Legislations by Prevalence of E-Cigarettes",
         xaxis = list(title = "Total Prevalence"),
         yaxis = list(title = "Total Legislations")) 

```


### Description

