---
title: "Visualizations"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(viridis)
ecig_data = read.csv("./Data/ecig_data.csv")
```


```{r, echo = F, message = F}
years = ecig_data %>% distinct(year) %>% pull()
selectInput (
  "Year",
  label = h3("Select Year"),
  choices = years,
  selected = "2018"
)

renderPrint ({
  input[["Year"]]
})

```



### quit cig by prop ecigs

```{r, echo = F}
renderPlotly ({
  
  ecig_data %>% 
  mutate(harm_ecigs = recode(harm_ecigs,
                              "equally addictive" = "equally", "less addictive" = "less", "more addictive" = "more"), 
         ecigs_past_month = factor(ecigs_past_month,
                                   c(NA, "0", "1-2", "3-5", "6-9", "10-19", "20-29", "30"))) %>%
  filter(quit_cig != "not a smoker", 
         !is.na(quit_cig), 
         !is.na(ecigs_past_month)) %>% 
  filter(year == input$Year) %>%
  group_by(quit_cig, ecigs_past_month) %>% 
  summarise(n= n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  plot_ly(
    x = ~quit_cig, y = ~prop,  color = ~ecigs_past_month,
    type = "bar", mode = "markers"
  )  
  
})
    
```


### try ecigs by smoking status
```{r, echo = F}
renderPlotly ({
  
  ecig_data %>%
  filter(year == input$Year) %>%
  filter(is.na(age) == FALSE, is.na(try_ecigs) == FALSE, is.na(cig_days) == FALSE) %>%
  mutate(current_cig = as.numeric(cig_days != "0")) %>%
  mutate(current_cig = as.factor(current_cig)) %>%
  group_by(age, current_cig) %>%
  mutate(indc = ifelse(try_ecigs == "yes", 1, 0)) %>%
  summarise(y = weighted.mean(indc, as.numeric(weight))) %>%
  plot_ly(
    x = ~age, y = ~y, color = ~current_cig,
    type = "scatter", mode = "markers"
  ) 
    
  
})

```


```{r, echo = F}
renderPlotly({
  
  ecig_data %>%
  filter(year == input$Year) %>%
  filter(is.na(age) == FALSE, is.na(sex) == FALSE, is.na(try_ecigs) == FALSE) %>%
  group_by(age, sex) %>%
  mutate(indc = ifelse(try_ecigs == "yes", 1, 0)) %>%
  summarise(y = weighted.mean(indc, as.numeric(weight))) %>%
  plot_ly(
    x = ~age, y = ~y, color = ~sex,
    type = "bar", position = "dodge"
  )
  
  
})

```



