---
title: "ecig state prevalence"
author: "Charlotte Fowler"
date: "11/15/2019"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```


```{r}
url = "https://www.cdc.gov/pcd/issues/2019/18_0362.htm"

state_prev_xml = read_html(url)

state_prev = 
  (state_prev_xml %>% html_nodes(css = "table")) %>% 
  .[[1]] %>%
  html_table(fill = TRUE) #%>% 
 #rename (state = names(.)[1])

names(state_prev)[1] = "state"
names(state_prev)[2] = "ex1"
names(state_prev)[3] = "ex2"
names(state_prev)[4] = "ex3"
names(state_prev)[5] = "ex4"
names(state_prev)[6] = "ex5"
names(state_prev)[8] = "total_prev"
names(state_prev)[9] = "male_prev"
names(state_prev)[10] = "female_prev"
 

state_prev = state_prev %>% 
  select(state, total_prev, male_prev, female_prev) %>% 
  slice(3:n())  %>% 
  separate(state, into = c("state", "n"), "\\(") %>% 
  separate(total_prev, into = c("total_prev", "total_CI"), "\\(" ) %>% 
  separate(male_prev, into = c("male_prev", "male_CI"), "\\(" ) %>% 
  separate(female_prev, into = c("female_prev", "female_CI"), "\\(" ) %>% 
  select(state, total_prev, male_prev, female_prev)

```


```{r}
names(table_current_use)[8]
```

