---
title: "map"
author: "Rebecca Silva"
date: "11/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)
library(plotly)
library(gganimate)
#library(animation)

```


```{r}
# cleaning datasets 
states = map_data("state") %>% 
  rename(state = region) %>% 
  select(state, everything(), -subregion)
state_prev = 
  state_prev %>% 
  mutate(state = str_to_lower(state), 
         state = trimws(state), 
         total_prev = as.numeric(total_prev), 
         male_prev = as.numeric(male_prev), 
         female_prev = as.numeric(female_prev))

legislation_data = 
  legislation_data %>%
  mutate(location_desc = str_to_lower(location_desc)) %>% 
  rename(state = location_desc)

# joining datasets 
map_state_prev = left_join(states, state_prev, by = "state")


# remove NAs
map_data = 
  map_data %>% 
  filter(!is.na(effective_date)) 
```


want: state, year, prevalence, legislation

```{r}
## prevalence map

prev_plot = map_state_prev  %>% 
  ggplot() +
  geom_polygon(aes( x = long, y = lat, group = group, fill = total_prev, subgroup = state), color = "white") +
  scale_fill_continuous(low = "white", high = "red", na.value = "black") +
  labs(
    title = "Prevalence of E-cigarette use by state",
    fill = "Prevalence", 
    x = "", 
    y = "")

p = ggplotly(prev_plot, tooltip = c("state", "total_prev")) 


```

Over the years - plotly 

```{r, options(error=recover)}
non_leg_map_data = 
  map_data %>% 
  select(-effective_date) %>% 
  distinct(year, state, long, lat, total_prev, group)

year_plot = 
  non_leg_map_data %>% 
  ggplot() +
  geom_polygon(aes( x = long, y = lat, group = group, fill = total_prev), color = "white") +
  scale_fill_continuous(low = "white", high = "red", na.value = "black") +
  labs(fill = "Prevalence") +
  transition_reveal(year, keep_last = FALSE)


non_leg_map_data %>% 
  ggplot() +
  geom_polygon(aes( x = long, y = lat, group = group, fill = total_prev), color = "white") +
  scale_fill_continuous(low = "white", high = "red", na.value = "black") +
  labs(fill = "Prevalence") +
  transition_states(year, wrap = FALSE)

non_leg_map_data %>% 
  ggplot() +
  geom_polygon(aes( x = long, y = lat, group = group, fill = total_prev), color = "white") +
  scale_fill_continuous(low = "white", high = "red", na.value = "black") +
  labs(fill = "Prevalence") %>% 
  tm_facets(along = "year")

library(tmap)
p = ggplotly(year_plot) 
g + plot_ly(data = non_leg_map_data, aes( frame = ~year))


+
  labs(title = 'Year: {frame_time}', 
       x = 'GDP per capita',
       y = 'life expectancy') +
  transition_time(year) 




```

```{r}
legislation_n = legislation_data %>% 
  group_by(year, state, effective_date) %>% 
  summarise(n_legislation = n()) %>% 
  filter(!is.na(effective_date)) %>% 
  select(-effective_date)

map_data_leg = left_join(states, legislation_n, by = "state")
g = 
  map_data_leg %>% 
  ggplot() +
  geom_polygon(aes( x = long, y = lat, group = group, fill = n_legislation, subgroup = year), color = "white") +
  scale_fill_continuous(low = "white", high = "red", na.value = "black") +
  labs(fill = "# Legislations") +
  transition_states(year, wrap = FALSE)
  
gb =  map_data_leg %>% 
  ggplot() +
  geom_polygon(aes( x = long, y = lat, group = group, fill = n_legislation), color = "white") +
  scale_fill_continuous(low = "white", high = "red", na.value = "black") +
  transition_states(year, wrap = FALSE) +
  labs(title = 'Year: {closest_state}', 
       fill = "# Legislations")

animate(gb) # this one



```

