---
title: "E-cigarette use among youth in the United States from 2003-2018"
author: "Robert Tumasian (rat2134), Rebecca Silva (rs4025), Charlotte Fowler (crf2147) and Madison Stoms (ms5975)"
output: github_document
---
## Motivation
E-cigarettes have become a growing public health concern. As of October 29, 2019, 1,888 cases of lung injury due to e-cigarette use, or vaping, have been reported to the CDC from 49 states [(1)](https://www.cdc.gov/tobacco/basic_information/e-cigarettes/severe-lung-disease.html). Medical officials have become increasingly interested in the development of lung disease among users; however, there is still little known about this topic. While e-cigarettes and vapes were initially intended for current smokers to reduce tobacco dependency, these products have been largely marketed to teenagers with no smoking history. The goal of this project is to better understand trends in e-cigarette use among youth in order to inform the development and implementation of preventive and therapeutic interventions.

## Intended Final Products
We will create a website with various exploratory plots and a shiny app containing an interactive U.S. map showing e-cigarette trends and legislation across states and years.

## Data Sources
Our main data source will be the National Youth Tobacco Survey provided by the CDC from 1999-2018 [(2)](https://www.cdc.gov/tobacco/data_statistics/surveys/nyts/data/index.html). Each observation represents an individual and each year contains about 15,000-20,000 individuals with ~300 variables. We will also look into the legislation data [(3)](https://catalog.data.gov/dataset/cdc-state-system-e-cigarette-legislation-youth-access-a2edb), which provide information on each legislative attempt to control or restrict electronic cigarettes in the United States.

## Planned Analyses / Visualizations / Coding Challenges

Some questions of interest:

* When and how did vaping move away from the target population of tobacco addicts to young non-smokers?  

* Is vaping an urban or rural phenomenon, and how has legislation in each state affected e-cigarette use? 

* Do states with certain legislation or higher quantity of legislation have a lower prevalence of e-cigarette use? 

* How does the proportion of people using e-cigarettes to quit smoking differ between age groups?

We will use several visualizations to address our questions of interest. For example, we will create a map displaying e-cigarette use and legislation among states and years. We anticipate that many of our coding challenges will come from merging the datasets across years.

## Timeline
Nov. 5 - Nov 15: Data cleaning and exploration  
Nov. 16- 24: Visualization  
Nov. 24 - 29: Analysis  
Nov 30 - Dec. 2: Write-up  
Dec. 2 - 5: Screencast  
